### ISSUE TITLE
Authentication error with Zimbra 8.8.15_GA_3829 (build 20190718141144)

### ISSUE THREAD

**Issue by edhil** [irontec/zmantis#6]
Hi Kaian, 
We have an authentication issue after upgrading zimbra to 8.8.15.
Maybe a new  jquery issue ?

**Comment by Kaian** [comment]
Hi @edhil 

I have never tested with that version but, the most common problem usually is not having JspEnabled (Check #1 issue)

```
root@zimbra8-dev:# su - zimbra
zimbra@zimbra8-dev:$ zmprov gs zimbra8-dev.irontec.com | grep zimbraZimletJspEnabled
(should be FALSE)
zimbra@zimbra8-dev:$ zmprov ms zimbra8-dev.irontec.com zimbraZimletJspEnabled TRUE
zimbra@zimbra8-dev:$ zmcontrol restart
```

(replace *zimbra8-dev.irontec.com* with your server name)

**Comment by edhil** [comment]
Hi Kaian, 
Thanks for your return. Unfortunately JspEnabled is already  TRUE. 
Actually the zimlet was working before the update, so I suspect some change  due to the upgrade. 

I will try to disable/enable JSP and let you know if there is a change.

**Comment by Kaian** [comment]
Try to debug with a browser inspector (google inspector, firebug, etc) the response to requests done by redirect.jsp

That can also give you some clues.

Regarding

**Comment by edhil** [comment]
Hi Kaian, 
I did some test, but all I get is an error 500 : 

/service/zimlet/com_irontec_zmantis/src/redirect.jsp:1 Failed to load resource: the server responded with a status of 500 (Server Error)
11:04:30.843 Zimlets-nodev_all.js.zgz?language=fr&country=FR&cosId=c00bbdb0-90c2-4b5b-b55f-057e2b2ae619:11676 Uncaught TypeError: Cannot read property 'getElementsByTagName' of null
    at Function.SOAPClient._getElementsByTagName (Zimlets-nodev_all.js.zgz?language=fr&country=FR&cosId=c00bbdb0-90c2-4b5b-b55f-057e2b2ae619:11676)
    at Function.SOAPClient._onSendSoapRequest (Zimlets-nodev_all.js.zgz?language=fr&country=FR&cosId=c00bbdb0-90c2-4b5b-b55f-057e2b2ae619:11568)
    at XMLHttpRequest.s.onreadystatechange (Zimlets-nodev_all.js.zgz?language=fr&country=FR&cosId=c00bbdb0-90c2-4b5b-b55f-057e2b2ae619:11559)
11:04:31.824 

For the record, we had also some issues with this zimbra version with RSS / Atom feed  due to a new feature : zimbra_feed_manager_blacklist.

**Comment by edhil** [comment]
Hi again, 
The zmmailboxd.out may be more explicit : 

2019-10-02 11:20:19.506:WARN:oejs.HttpChannel:qtp961409111-22339: /service/zimlet/com_irontec_zmantis/src/redirect.jsp
javax.servlet.ServletException: org.apache.jasper.JasperException: Unable to compile class for JSP: ||An error occurred at line: [78] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|org.apache.commons.httpclient.Cookie cannot be resolved to a type|75: |76:             // Get Post Cookies|77:             javax.servlet.http.Cookie reqCookie[] = request.getCookies();|78:             org.apache.commons.httpclient.Cookie[] clientCookie = new org.apache.commons.httpclient.Cookie[reqCookie.length];|79:             String hostName = request.getServerName () + ":" + request.getServerPort();|80: |81:             for (int i=0; i<reqCookie.length; i++) {|||An error occurred at line: [78] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|org.apache.commons.httpclient.Cookie cannot be resolved to a type|75: |76:             // Get Post Cookies|77:             javax.servlet.http.Cookie reqCookie[] = request.getCookies();|78:             org.apache.commons.httpclient.Cookie[] clientCookie = new org.apache.commons.httpclient.Cookie[reqCookie.length];|79:             String hostName = request.getServerName () + ":" + request.getServerPort();|80: |81:             for (int i=0; i<reqCookie.length; i++) {|||An error occurred at line: [83] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|org.apache.commons.httpclient.Cookie cannot be resolved to a type|80: |81:             for (int i=0; i<reqCookie.length; i++) {|82:                 javax.servlet.http.Cookie cookie = reqCookie[i];|83:                 clientCookie[i] = new org.apache.commons.httpclient.Cookie (hostName,cookie.getName(), cookie.getValue(),"/",null,false);|84:             }|85: |86:             // Get Connection State|||An error occurred at line: [87] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|HttpState cannot be resolved to a type|84:             }|85: |86:             // Get Connection State|87:             HttpState state = new HttpState();|88:             state.addCookies (clientCookie);|89: |90:              // Create a HTTP client with the actual state |||An error occurred at line: [87] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|HttpState cannot be resolved to a type|84:             }|85: |86:             // Get Connection State|87:             HttpState state = new HttpState();|88:             state.addCookies (clientCookie);|89: |90:              // Create a HTTP client with the actual state |||An error occurred at line: [91] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|HttpClient cannot be resolved to a type|88:             state.addCookies (clientCookie);|89: |90:              // Create a HTTP client with the actual state |91:             HttpClient srcClient = new HttpClient();|92:             Enumeration headerNamesImg = request.getHeaderNames();|93:             while(headerNamesImg.hasMoreElements()) {|94:                String headerNameImg = (String)headerNamesImg.nextElement();|||An error occurred at line: [91] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|HttpClient cannot be resolved to a type|88:             state.addCookies (clientCookie);|89: |90:              // Create a HTTP client with the actual state |91:             HttpClient srcClient = new HttpClient();|92:             Enumeration headerNamesImg = request.getHeaderNames();|93:             while(headerNamesImg.hasMoreElements()) {|94:                String headerNameImg = (String)headerNamesImg.nextElement();|||An error occurred at line: [104] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|URIUtil cannot be resolved|101:             String filename = attUrl.substring(0, paramsbeg);|102:             String getparam = attUrl.substring(paramsbeg, attUrl.length());|103:             getparam = getparam.replaceAll("&amp;","&");|104:             attUrl = URIUtil.encodePath(filename, "ISO-8859-1") + getparam;|105: |106:             // Download the Attachment|107:             GetMethod get = new GetMethod (attUrl);|||An error occurred at line: [107] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|GetMethod cannot be resolved to a type|104:             attUrl = URIUtil.encodePath(filename, "ISO-8859-1") + getparam;|105: |106:             // Download the Attachment|107:             GetMethod get = new GetMethod (attUrl);|108:             get.setFollowRedirects (true);|109:             srcClient.getHttpConnectionManager().getParams().setConnectionTimeout (10000);|110:             srcClient.executeMethod(get);|||An error occurred at line: [107] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|GetMethod cannot be resolved to a type|104:             attUrl = URIUtil.encodePath(filename, "ISO-8859-1") + getparam;|105: |106:             // Download the Attachment|107:             GetMethod get = new GetMethod (attUrl);|108:             get.setFollowRedirects (true);|109:             srcClient.getHttpConnectionManager().getParams().setConnectionTimeout (10000);|110:             srcClient.executeMethod(get);|||An error occurred at line: [138] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|HttpClient cannot be resolved to a type|135:     }|136: |137:     // Create a HTTP client to foward SOAP petition|138:     HttpClient client = new HttpClient();|139:     Enumeration headerNames = request.getHeaderNames();|140:     while(headerNames.hasMoreElements()) {|141:         String headerName = (String)headerNames.nextElement();|||An error occurred at line: [138] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|HttpClient cannot be resolved to a type|135:     }|136: |137:     // Create a HTTP client to foward SOAP petition|138:     HttpClient client = new HttpClient();|139:     Enumeration headerNames = request.getHeaderNames();|140:     while(headerNames.hasMoreElements()) {|141:         String headerName = (String)headerNames.nextElement();|||An error occurred at line: [148] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|PostMethod cannot be resolved to a type|145:     BufferedReader br = null;|146: |147:     // Set the input data for POST method|148:     PostMethod pmethod = new PostMethod(endPoint);|149: |150:     try{|151:         pmethod.setRequestEntity(new org.apache.commons.httpclient.methods.ByteArrayRequestEntity(ba,request.getContentType()));|||An error occurred at line: [148] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|PostMethod cannot be resolved to a type|145:     BufferedReader br = null;|146: |147:     // Set the input data for POST method|148:     PostMethod pmethod = new PostMethod(endPoint);|149: |150:     try{|151:         pmethod.setRequestEntity(new org.apache.commons.httpclient.methods.ByteArrayRequestEntity(ba,request.getContentType()));|||An error occurred at line: [151] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|org.apache.commons.httpclient.methods.ByteArrayRequestEntity cannot be resolved to a type|148:     PostMethod pmethod = new PostMethod(endPoint);|149: |150:     try{|151:         pmethod.setRequestEntity(new org.apache.commons.httpclient.methods.ByteArrayRequestEntity(ba,request.getContentType()));|152: |153:         int returnCode = client.executeMethod(pmethod);|154: |||An error occurred at line: [155] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|HttpStatus.SC_NOT_IMPLEMENTED cannot be resolved to a type|152: |153:         int returnCode = client.executeMethod(pmethod);|154: |155:         if(returnCode == HttpStatus.SC_NOT_IMPLEMENTED) {|156:             out.println("The Post method is not implemented by this URI");|157:             // still consume the response body|158:             pmethod.getResponseBodyAsString();|||Stacktrace:
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:168)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
	at org.eclipse.jetty.server.handler.DebugHandler.handle(DebugHandler.java:83)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: 
org.apache.jasper.JasperException: Unable to compile class for JSP: ||An error occurred at line: [78] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|org.apache.commons.httpclient.Cookie cannot be resolved to a type|75: |76:             // Get Post Cookies|77:             javax.servlet.http.Cookie reqCookie[] = request.getCookies();|78:             org.apache.commons.httpclient.Cookie[] clientCookie = new org.apache.commons.httpclient.Cookie[reqCookie.length];|79:             String hostName = request.getServerName () + ":" + request.getServerPort();|80: |81:             for (int i=0; i<reqCookie.length; i++) {|||An error occurred at line: [78] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|org.apache.commons.httpclient.Cookie cannot be resolved to a type|75: |76:             // Get Post Cookies|77:             javax.servlet.http.Cookie reqCookie[] = request.getCookies();|78:             org.apache.commons.httpclient.Cookie[] clientCookie = new org.apache.commons.httpclient.Cookie[reqCookie.length];|79:             String hostName = request.getServerName () + ":" + request.getServerPort();|80: |81:             for (int i=0; i<reqCookie.length; i++) {|||An error occurred at line: [83] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|org.apache.commons.httpclient.Cookie cannot be resolved to a type|80: |81:             for (int i=0; i<reqCookie.length; i++) {|82:                 javax.servlet.http.Cookie cookie = reqCookie[i];|83:                 clientCookie[i] = new org.apache.commons.httpclient.Cookie (hostName,cookie.getName(), cookie.getValue(),"/",null,false);|84:             }|85: |86:             // Get Connection State|||An error occurred at line: [87] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|HttpState cannot be resolved to a type|84:             }|85: |86:             // Get Connection State|87:             HttpState state = new HttpState();|88:             state.addCookies (clientCookie);|89: |90:              // Create a HTTP client with the actual state |||An error occurred at line: [87] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|HttpState cannot be resolved to a type|84:             }|85: |86:             // Get Connection State|87:             HttpState state = new HttpState();|88:             state.addCookies (clientCookie);|89: |90:              // Create a HTTP client with the actual state |||An error occurred at line: [91] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|HttpClient cannot be resolved to a type|88:             state.addCookies (clientCookie);|89: |90:              // Create a HTTP client with the actual state |91:             HttpClient srcClient = new HttpClient();|92:             Enumeration headerNamesImg = request.getHeaderNames();|93:             while(headerNamesImg.hasMoreElements()) {|94:                String headerNameImg = (String)headerNamesImg.nextElement();|||An error occurred at line: [91] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|HttpClient cannot be resolved to a type|88:             state.addCookies (clientCookie);|89: |90:              // Create a HTTP client with the actual state |91:             HttpClient srcClient = new HttpClient();|92:             Enumeration headerNamesImg = request.getHeaderNames();|93:             while(headerNamesImg.hasMoreElements()) {|94:                String headerNameImg = (String)headerNamesImg.nextElement();|||An error occurred at line: [104] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|URIUtil cannot be resolved|101:             String filename = attUrl.substring(0, paramsbeg);|102:             String getparam = attUrl.substring(paramsbeg, attUrl.length());|103:             getparam = getparam.replaceAll("&amp;","&");|104:             attUrl = URIUtil.encodePath(filename, "ISO-8859-1") + getparam;|105: |106:             // Download the Attachment|107:             GetMethod get = new GetMethod (attUrl);|||An error occurred at line: [107] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|GetMethod cannot be resolved to a type|104:             attUrl = URIUtil.encodePath(filename, "ISO-8859-1") + getparam;|105: |106:             // Download the Attachment|107:             GetMethod get = new GetMethod (attUrl);|108:             get.setFollowRedirects (true);|109:             srcClient.getHttpConnectionManager().getParams().setConnectionTimeout (10000);|110:             srcClient.executeMethod(get);|||An error occurred at line: [107] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|GetMethod cannot be resolved to a type|104:             attUrl = URIUtil.encodePath(filename, "ISO-8859-1") + getparam;|105: |106:             // Download the Attachment|107:             GetMethod get = new GetMethod (attUrl);|108:             get.setFollowRedirects (true);|109:             srcClient.getHttpConnectionManager().getParams().setConnectionTimeout (10000);|110:             srcClient.executeMethod(get);|||An error occurred at line: [138] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|HttpClient cannot be resolved to a type|135:     }|136: |137:     // Create a HTTP client to foward SOAP petition|138:     HttpClient client = new HttpClient();|139:     Enumeration headerNames = request.getHeaderNames();|140:     while(headerNames.hasMoreElements()) {|141:         String headerName = (String)headerNames.nextElement();|||An error occurred at line: [138] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|HttpClient cannot be resolved to a type|135:     }|136: |137:     // Create a HTTP client to foward SOAP petition|138:     HttpClient client = new HttpClient();|139:     Enumeration headerNames = request.getHeaderNames();|140:     while(headerNames.hasMoreElements()) {|141:         String headerName = (String)headerNames.nextElement();|||An error occurred at line: [148] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|PostMethod cannot be resolved to a type|145:     BufferedReader br = null;|146: |147:     // Set the input data for POST method|148:     PostMethod pmethod = new PostMethod(endPoint);|149: |150:     try{|151:         pmethod.setRequestEntity(new org.apache.commons.httpclient.methods.ByteArrayRequestEntity(ba,request.getContentType()));|||An error occurred at line: [148] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|PostMethod cannot be resolved to a type|145:     BufferedReader br = null;|146: |147:     // Set the input data for POST method|148:     PostMethod pmethod = new PostMethod(endPoint);|149: |150:     try{|151:         pmethod.setRequestEntity(new org.apache.commons.httpclient.methods.ByteArrayRequestEntity(ba,request.getContentType()));|||An error occurred at line: [151] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|org.apache.commons.httpclient.methods.ByteArrayRequestEntity cannot be resolved to a type|148:     PostMethod pmethod = new PostMethod(endPoint);|149: |150:     try{|151:         pmethod.setRequestEntity(new org.apache.commons.httpclient.methods.ByteArrayRequestEntity(ba,request.getContentType()));|152: |153:         int returnCode = client.executeMethod(pmethod);|154: |||An error occurred at line: [155] in the jsp file: [/com_irontec_zmantis/src/redirect.jsp]|HttpStatus.SC_NOT_IMPLEMENTED cannot be resolved to a type|152: |153:         int returnCode = client.executeMethod(pmethod);|154: |155:         if(returnCode == HttpStatus.SC_NOT_IMPLEMENTED) {|156:             out.println("The Post method is not implemented by this URI");|157:             // still consume the response body|158:             pmethod.getResponseBodyAsString();|||Stacktrace:
	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:102)
	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:212)
	at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:549)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:378)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:350)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:334)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:595)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:399)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:227)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:78)
	at com.zimbra.cs.zimlet.ZimletResources.service(ZimletResources.java:143)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at com.zimbra.cs.servlet.RequestStringFilter.doFilter(RequestStringFilter.java:54)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at com.zimbra.cs.zimlet.ZimletFilter.doFilter(ZimletFilter.java:243)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:59)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at com.zimbra.cs.servlet.ETagHeaderFilter.doFilter(ETagHeaderFilter.java:47)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at com.zimbra.cs.servlet.ContextPathBasedThreadPoolBalancerFilter.doFilter(ContextPathBasedThreadPoolBalancerFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at com.zimbra.cs.servlet.ThrottlingFilter.doFilter(ThrottlingFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter(ZimbraQoSFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at com.zimbra.cs.servlet.ZimbraInvalidLoginFilter.doFilter(ZimbraInvalidLoginFilter.java:131)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:482)
	at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:327)
	at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:297)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
	at org.eclipse.jetty.server.handler.DebugHandler.handle(DebugHandler.java:83)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Kaian** [comment]
According to the last log you added

```org.apache.commons.httpclient.Cookie cannot be resolved to a type```

Current code seem to use that class [here](https://github.com/irontec/zmantis/blob/master/src/redirect.jsp#L78), but it's not longer available in Zimbra 8.8.

So, current implementation is not compatible with newest Zimbra. As you can see, this project last commit is from more than 3 years ago. We're no longer using or updating it, but feel free to contact anyone with some basic zimlet dev knowledge to fix it!

Thanks for your patience!

**Comment by edhil** [comment]
Well, according to the jar files, the HttpClient API has been changed from 3.x to 4.x version. 
My java is a bit rusty, but I'll check if I can make the necessary changes. 
Thanks for your help anyway.

**Comment by maxxer** [comment]
> Well, according to the jar files, the HttpClient API has been changed from 3.x to 4.x version.
> My java is a bit rusty, but I'll check if I can make the necessary changes.
> Thanks for your help anyway.

Did you ever manage to create a fix? Thanks

**Comment by maxxer** [comment]
Found commit 8a10a94ec47c0cb68f42 which should solve this issue

**Comment by edhil** [comment]
Yep this commit is a workaround wich fix the issue by embedding the old httpclient class
I did use the same hack for a while and it did work. But now I have another issue, as it seems to break compatibility with newer Zimbra Connect (chat system) zimlet. 

I'll probably open a new issue for that, however. 


> Found commit [8a10a94](https://github.com/irontec/zmantis/commit/8a10a94ec47c0cb68f4232de1154cee51f52747d) which should solve this issue
